# Generated by Django 3.1.5 on 2021-03-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='problem',
            new_name='contest_reference',
        ),
    ]
