# Generated by Django 3.1.5 on 2021-03-26 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210316_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='testfile',
            field=models.FileField(default=django.utils.timezone.now, upload_to='testfile/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_name',
            field=models.TextField(max_length=200),
        ),
    ]
