# Generated by Django 3.1.5 on 2021-03-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210326_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_definition',
            field=models.TextField(max_length=700),
        ),
    ]
