# Generated by Django 3.1.5 on 2021-03-31 13:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_coder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coder',
            new_name='Profile',
        ),
    ]
