# Generated by Django 3.1.5 on 2021-04-07 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20210331_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem_Solved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_get', models.IntegerField(default=0)),
                ('contest_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contest')),
                ('problem_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.problem')),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
