# Generated by Django 3.1.5 on 2021-04-08 08:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_problem_solved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problem_solved',
            unique_together={('user_ref', 'problem_ref')},
        ),
    ]
