# Generated by Django 3.1.5 on 2021-04-08 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210408_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem_solved',
            name='time_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
