# Generated by Django 3.1.5 on 2021-04-09 07:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_problem_solved_time_submitted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problem_Solved',
            new_name='ProblemSolved',
        ),
    ]
