# Generated by Django 3.2 on 2021-04-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210409_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='inputfile',
            field=models.FileField(default='C:\\django projects\\Codemania\\static\\images', upload_to='inputfile/'),
            preserve_default=False,
        ),
    ]
