# Generated by Django 3.2 on 2021-04-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_problem_inputfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
